# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-30 02:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name=b'Nombre')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100, verbose_name=b'Cliente')),
                ('contacto', models.CharField(max_length=100, verbose_name=b'Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Telefono')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Celular')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Email')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Direccion')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Fecha entrada')),
            ],
            options={
                'ordering': ('cliente',),
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='ComentarioCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name=b'Comentario')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Fecha')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Cliente')),
            ],
            options={
                'verbose_name_plural': 'Comentarios Cliente',
            },
        ),
        migrations.CreateModel(
            name='ComentarioPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name=b'Comentario')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Fecha')),
            ],
            options={
                'verbose_name_plural': 'Comentarios Pedido',
            },
        ),
        migrations.CreateModel(
            name='ComentarioProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name=b'Comentario')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Fecha')),
            ],
            options={
                'verbose_name_plural': 'Comentarios Producto',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name=b'Nombre')),
            ],
            options={
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='EtiquetasProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.ImageField(upload_to=b'etiquetas/')),
                ('nombre', models.CharField(max_length=250, verbose_name=b'Nombre')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Fecha gasto')),
                ('total', models.FloatField(default=0, verbose_name=b'Total')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
                ('autorizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Gastos del dia',
            },
        ),
        migrations.CreateModel(
            name='MetodoEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_envio', models.CharField(max_length=150, verbose_name=b'Metodo envio')),
            ],
            options={
                'verbose_name_plural': 'Metodos de Envio',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(max_length=20, verbose_name=b'Metodo pago')),
            ],
            options={
                'verbose_name_plural': 'Metodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_de_venta', models.CharField(max_length=50, verbose_name=b'Orden de Venta')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Fecha pedido')),
                ('direccion_envio', models.CharField(max_length=250, verbose_name=b'Direccion envio')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Telefono')),
                ('mail', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Mail')),
                ('total', models.FloatField(default=0, verbose_name=b'Total')),
                ('armado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armado_por', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Cliente')),
                ('emitido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emitido_por', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Estado')),
                ('metodo_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.MetodoEnvio')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.MetodoPago')),
            ],
            options={
                'verbose_name_plural': 'Ventas del dia',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name=b'Nombre')),
                ('precio_venta_distribuidor', models.FloatField(default=0, verbose_name=b'Precio Venta Distribuidor')),
                ('precio_venta_publico', models.FloatField(default=0, verbose_name=b'Precio Venta Publico')),
                ('precio_costo', models.FloatField(default=0, verbose_name=b'Precio Costo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.Categoria')),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta_distribuidor', models.FloatField(default=0, verbose_name=b'Precio')),
                ('cantidad_productos', models.FloatField(default=0, verbose_name=b'Cantidad')),
                ('descuento', models.FloatField(default=0, verbose_name=b'Descuento')),
                ('total', models.FloatField(default=0, verbose_name=b'Total')),
                ('comentario', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Comentario')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Producto')),
            ],
            options={
                'verbose_name_plural': 'Articulos del Pedido',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=100, verbose_name=b'Proveedor')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Telefono')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Celular')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Email')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Direccion')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Fecha entrada')),
            ],
            options={
                'ordering': ('proveedor',),
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Fecha')),
                ('inicial', models.IntegerField(default=0, verbose_name=b'Inicial')),
                ('actual', models.IntegerField(default=0, verbose_name=b'Actual')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Producto')),
            ],
            options={
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name=b'Nombre')),
                ('usuarios', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gasto', models.CharField(max_length=30, verbose_name=b'Tipo de Gasto')),
            ],
            options={
                'verbose_name_plural': 'Tipos de gasto',
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Sucursal'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Sucursal'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.MetodoPago'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Proveedor'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Sucursal'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='tipo_gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.TipoGasto'),
        ),
        migrations.AddField(
            model_name='etiquetasproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Producto'),
        ),
        migrations.AddField(
            model_name='comentarioproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Producto'),
        ),
        migrations.AddField(
            model_name='comentariopedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Pedido'),
        ),
    ]
