# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-10 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='sucursal',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ventas.Sucursal'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='sucursal',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ventas.Sucursal'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sucursal',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ventas.Sucursal'),
        ),
    ]
