# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-10 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20171010_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='usuarios',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='sucursal',
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
