# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-24 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20171010_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.IntegerField(default=0, verbose_name=b'Orden'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='shop',
            field=models.BooleanField(default=False, verbose_name=b'Shop'),
        ),
    ]
