# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-28 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20171103_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to=b'imgProd/')),
                ('principal', models.BooleanField(default=False, verbose_name=b'Principal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Producto')),
            ],
            options={
                'verbose_name_plural': 'Imagenes Producto',
            },
        ),
    ]
