# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-02 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stocks',
            field=models.FloatField(default=0, verbose_name=b'Stock'),
        ),
    ]
